apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: rahultanwar/frontend-py:latest # Replace with your actual frontend image name
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer  # Change from ClusterIP to LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: frontend

